# Generated by Django 5.0.4 on 2024-04-07 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.group'),
        ),
    ]
