# Generated by Django 5.0.4 on 2024-04-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_profile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
